// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package projects

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/molnarjani/yonash-dev/internal/web/templates/components"

func YonashHomeProject() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"max-w-4xl mx-auto space-y-8\"><!-- Header Section --><div class=\"text-center\"><h1 class=\"text-3xl md:text-4xl font-bold text-gray-900 dark:text-white mb-4\">yonash.home</h1><p class=\"text-lg text-gray-600 dark:text-gray-300 mb-8\">Self-hosted homeserver with multimedia services</p></div><!-- Hero Image --><div class=\"rounded-lg overflow-hidden shadow-xl\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Image("images/yonash-home.webp", templ.Attributes{
				"class": "w-full h-auto",
				"alt":   "yonash.home server dashboard",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><!-- Project Description --><div class=\"prose prose-lg max-w-none dark:prose-invert\"><p class=\"text-gray-700 dark:text-gray-300 leading-relaxed\">This is a self-hosted Linux server accessible from my local network, where I host multimedia services and home automation tools.  It serves as the central hub for my smart home setup and personal cloud services.</p></div><!-- Services Section --><div class=\"bg-gray-50 dark:bg-gray-800 rounded-lg p-6\"><h3 class=\"text-xl font-semibold text-gray-900 dark:text-white mb-6\">Hosted Services</h3><div class=\"space-y-4\"><div class=\"flex items-start space-x-3 p-4 bg-white dark:bg-gray-700 rounded-lg\"><div class=\"w-2 h-2 bg-blue-500 rounded-full mt-2\"></div><div><div class=\"font-medium text-gray-900 dark:text-white\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Link("https://heimdall.site/", "Heimdall").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"text-gray-600 dark:text-gray-400 text-sm\">Homeserver landing page UI for easy access to all services</div></div></div><div class=\"flex items-start space-x-3 p-4 bg-white dark:bg-gray-700 rounded-lg\"><div class=\"w-2 h-2 bg-green-500 rounded-full mt-2\"></div><div><div class=\"font-medium text-gray-900 dark:text-white\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Link("https://www.firefly-iii.org/", "Firefly III").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"text-gray-600 dark:text-gray-400 text-sm\">Finance manager app with automated credit card statement importing  (includes a custom @components.Link(\"https://github.com/molnarjani/raiffeisen-csv-processor\", \"CSV processor\") for bank exports)</div></div></div><div class=\"flex items-start space-x-3 p-4 bg-white dark:bg-gray-700 rounded-lg\"><div class=\"w-2 h-2 bg-purple-500 rounded-full mt-2\"></div><div><div class=\"font-medium text-gray-900 dark:text-white\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Link("https://www.home-assistant.io/", "Home Assistant").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("+ @components.Link(\"https://www.zigbee2mqtt.io/\", \"Zigbee2MQTT\")</div><div class=\"text-gray-600 dark:text-gray-400 text-sm\">Smart home automation platform for controlling lights and IoT devices</div></div></div><div class=\"flex items-start space-x-3 p-4 bg-white dark:bg-gray-700 rounded-lg\"><div class=\"w-2 h-2 bg-red-500 rounded-full mt-2\"></div><div><div class=\"font-medium text-gray-900 dark:text-white\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Link("https://deluge-torrent.org/", "Deluge").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("+ @components.Link(\"https://kodi.tv/\", \"Kodi\")</div><div class=\"text-gray-600 dark:text-gray-400 text-sm\">Torrent client and multimedia server for local content streaming</div></div></div></div></div><!-- Features Section --><div class=\"bg-blue-50 dark:bg-blue-900/20 rounded-lg p-6\"><h3 class=\"text-xl font-semibold text-gray-900 dark:text-white mb-4\">Key Features</h3><div class=\"grid grid-cols-1 md:grid-cols-2 gap-3\"><div class=\"flex items-center space-x-3\"><div class=\"w-2 h-2 bg-blue-500 rounded-full\"></div><span class=\"text-gray-700 dark:text-gray-300\">Self-hosted infrastructure</span></div><div class=\"flex items-center space-x-3\"><div class=\"w-2 h-2 bg-blue-500 rounded-full\"></div><span class=\"text-gray-700 dark:text-gray-300\">Home automation</span></div><div class=\"flex items-center space-x-3\"><div class=\"w-2 h-2 bg-blue-500 rounded-full\"></div><span class=\"text-gray-700 dark:text-gray-300\">Financial management</span></div><div class=\"flex items-center space-x-3\"><div class=\"w-2 h-2 bg-blue-500 rounded-full\"></div><span class=\"text-gray-700 dark:text-gray-300\">Media streaming</span></div><div class=\"flex items-center space-x-3\"><div class=\"w-2 h-2 bg-blue-500 rounded-full\"></div><span class=\"text-gray-700 dark:text-gray-300\">IoT integration</span></div><div class=\"flex items-center space-x-3\"><div class=\"w-2 h-2 bg-blue-500 rounded-full\"></div><span class=\"text-gray-700 dark:text-gray-300\">Local network access</span></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = components.ProjectContainer().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
